-- Esta migración quedó anulada: intentaba crear/alterar las mismas tablas de catálogo
-- (categorias_calidad, navieras, puertos, tipos_certificacion, entidades_certificadoras,
-- tipos_documento) que la migración posterior 20260802154500_add_domain_catalogs crea de
-- forma completa (con la migración de datos legados incluida). Al ejecutarse antes que esa
-- migración, dejaba las tablas de catálogo con columnas distintas y las columnas de texto
-- libre (categoria_calidad, categoria, tipo_certificacion, entidad_emisora, tipo, naviera,
-- puerto_origen, puerto_destino, pais_destino) ya eliminadas, lo que hacía fallar la
-- migración de datos legados de 20260802154500 en cualquier base que llegara a tenerlas.
-- En la práctica nunca pudo aplicarse con éxito en ninguna base (la migración posterior
-- también falla si esta corrió primero), así que se deja como no-op para no romper el
-- historial de migraciones ya registrado.
SELECT 1;
